### ISSUE TITLE
Eliminate remaining traces of styleguide copy

### ISSUE THREAD

**Issue by migurski** [mapzen/mapzen-docs-generator#109]
Styleguide should be used via public URL only. Remove dependency on https://github.com/mapzen/styleguide repository everywhere. @louh I’d love your help here!

**Comment by louh** [comment]
Are you talking about this here: https://github.com/mapzen/mapzen-docs-generator/blob/master/package.json#L20

This makes a copy of the styleguide so that templates can use the nav and footer fragments. We don't have a public URL for those. I'm not exactly sure what is the best way to do this otherwise without declaring the dependency. Should I just curl the raw file from git?

**Comment by migurski** [comment]
Yes, that’s the one!

A direct curl from a public URL would be perfect. This would allow us to excise any use of `npm` right?

**Comment by louh** [comment]
It looks like the Make is already curling the styleguide repository: https://github.com/mapzen/mapzen-docs-generator/blob/master/Makefile#L55-L60

`npm` usage might already be vestigial at this point.

**Comment by migurski** [comment]
Ah those are indeed just the fragments, that’s great. Going to assign this ticket to wrap this up.
